export const strings = {
  app: {
    title: 'Study',
    navQueue: 'Fila',
    navAdd: 'Adicionar',
    navItems: 'Lista',
    navStats: 'Stats',
    bootFailure: 'não foi possível abrir os dados; recarregue a página',
  },
  notice: {
    loading: 'carregando…',
  },
  status: {
    active: 'ativo',
    archived: 'arquivado',
    cold: 'no arquivo morto',
  },
  filterStatus: {
    active: 'ativos',
    archived: 'arquivados',
    cold: 'no arquivo morto',
    all: 'todos',
  },
  due: {
    prefix: 'Próxima revisão em',
    separator: ' — ',
    days: (count: number) => (count === 1 ? '1 dia' : `${count} dias`),
  },
  add: {
    heading: 'Adicionar item',
    titleLabel: 'título',
    subjectLabel: 'matéria',
    difficultyLabel: 'dificuldade',
    noteLabel: 'nota',
    linkLabel: 'link',
    previewLabel: 'próximo vencimento',
    submit: 'salvar',
    cancel: 'cancelar',
  },
  queue: {
    heading: 'Fila de hoje',
    empty: 'a fila está vazia',
    emptyAction: 'adicionar um item',
    summaryTotal: 'itens hoje',
    summaryLate: 'atrasados',
    summaryBySubject: 'por matéria',
    late: (days: number) => (days === 1 ? '1 dia de atraso' : `${days} dias de atraso`),
    dueToday: 'vence hoje',
  },
  items: {
    heading: 'Itens',
    searchLabel: 'buscar por título',
    subjectLabel: 'matéria',
    subjectAll: 'todas as matérias',
    statusLabel: 'status',
    empty: 'nenhum item encontrado',
    emptyAction: 'adicionar o primeiro item',
    open: 'abrir',
  },
  detail: {
    heading: 'Detalhe do item',
    titleField: 'título',
    subjectField: 'matéria',
    difficultyField: 'dificuldade',
    noteField: 'nota',
    linkField: 'link',
    dueDateField: 'próximo vencimento',
    statusField: 'status',
    streakField: 'check-ins consecutivos no prazo',
    none: 'nenhum',
    archive: 'arquivar',
    unarchive: 'desarquivar',
    review: 'fazer check-in',
  },
  review: {
    heading: 'Check-in',
    checkin: 'estudei agora',
    recorded: 'check-in registrado',
    reevaluate: 'reavaliar a dificuldade',
    difficultyLabel: 'dificuldade',
    apply: 'aplicar nova dificuldade',
    keep: 'manter a atual',
    openItem: 'abrir o item',
  },
  stats: {
    heading: 'Stats',
    streak: 'dias com fila zerada',
    active: 'ativos',
    archived: 'arquivados',
    cold: 'no arquivo morto',
    checkinsToday: 'check-ins de hoje',
    bySubject: 'check-ins por matéria',
  },
  errors: {
    store: 'não foi possível salvar; tente de novo',
    notFound: 'item não encontrado',
    invalidRef: 'referência inválida: use o título exato',
    ambiguousRef: 'há mais de um item com esse título',
    itemArchived: 'item arquivado; desarquive para revisar',
    itemCold: 'item no arquivo morto; restaure para revisar',
    alreadyArchived: 'item já está arquivado',
    alreadyActive: 'item já está ativo',
  },
  deps: {
    invalidInstant: 'instante inválido: use ISO 8601',
  },
} as const
